# Generated by Django 2.0.4 on 2018-04-26 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_auto_20180426_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cell',
            name='date',
            field=models.CharField(max_length=10, verbose_name='Дата ячейки'),
        ),
        migrations.AlterField(
            model_name='cell',
            name='free',
            field=models.BooleanField(default=True, verbose_name='Ячейка свободна'),
        ),
        migrations.AlterField(
            model_name='cell',
            name='time_end',
            field=models.CharField(max_length=5, verbose_name='Время окончания ячейки'),
        ),
        migrations.AlterField(
            model_name='cell',
            name='time_start',
            field=models.CharField(max_length=5, verbose_name='Время начала ячейки'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название клиники'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='ecpec',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Специальность врача'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='efio',
            field=models.CharField(max_length=150, verbose_name='Имя врача'),
        ),
    ]
