# Generated by Django 2.0.4 on 2018-04-26 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_auto_20180426_1106'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='cell',
            options={'verbose_name': 'Ячейкa', 'verbose_name_plural': 'Ячейки'},
        ),
        migrations.AlterModelOptions(
            name='clinic',
            options={'verbose_name': 'Клиника', 'verbose_name_plural': 'Клиники'},
        ),
        migrations.AlterModelOptions(
            name='doctor',
            options={'verbose_name': 'Доктор', 'verbose_name_plural': 'Доктора'},
        ),
        migrations.AlterField(
            model_name='cell',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.Doctor', verbose_name='Доктор'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.Clinic', verbose_name='Клиника'),
        ),
    ]
