# Generated by Django 2.0.4 on 2018-04-27 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_auto_20180426_1253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='ecpec',
            new_name='espec',
        ),
    ]
